name: clean_architecture
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.3
  #comparing dart object
  equatable: ^2.0.5
  #service Locator
  get_it: ^7.6.6
  #data formart
  intl: ^0.19.0
  #DataBase
  floor: ^1.4.2
  #make request to api
  retrofit: ^4.0.3
  #make reponse2
  dio: ^5.4.0
  #Hooks
  flutter_hooks: ^0.20.4
  #chached network image
  cached_network_image: ^3.3.1
  #Google fonts
  google_fonts: ^6.1.0
  ionicons: ^0.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2
  build_runner: ^2.4.8




flutter:

  uses-material-design: true


#  assets:
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
